deployTargetMap:
  dev01: !!com.boxboat.jenkins.library.deployTarget.KubernetesDeployTarget
    contextName: boxboat
    credential: kubeconfig-dev
  prod01: !!com.boxboat.jenkins.library.deployTarget.KubernetesDeployTarget
    contextName: boxboat
    credential: kubeconfig-prod
  prod02: !!com.boxboat.jenkins.library.deployTarget.KubernetesDeployTarget
    contextName: boxboat
    credential: kubeconfig-prod-02
environmentMap:
  dev:
    name: dev
    deployTargetKey: dev01
  prod:
    name: prod-a
    deployTargetKey: prod01
    replicaEnvironments:
      - name: prod-b
        deployTargetKey: prod02
git:
  buildVersionsUrl: git@github.com:boxboat/build-versions.git
  credential: git-creds
  email: bill@boxboat.com
  remotePathRegex: github\.com[:\/]billboggs\/(.*)\.git$
  remoteUrlReplace: git@github.com:billboggs/{{ path }}.git
  branchUrlReplace: https://github.com/billboggs/{{ path }}/tree/{{ branch }}
  commitUrlReplace: https://github.com/billboggs/{{ path }}/commit/{{ hash }}
notifyTargetMap:
  default: !!com.boxboat.jenkins.library.notify.SlackWebHookNotifyTarget
    credential: slack-webhook-url
registryMap:
  default:
    scheme: http
    host: test
    credential: registry
    imageUrlReplace: http://test
vaultMap:
  default:
    kvVersion: 1
    roleIdCredential: vault-role-id
    secretIdCredential: vault-secret-id
    tokenCredential: vault-token
    url: http://localhost:8200
awsProfileMap:
  default:
    region: us-east-1
    accessKeyIdCredential: aws-access-key-id
    secretAccessKeyCredential: aws-secret-access-key

repo:
  common:
    defaultBranch: master
    notify:
      targetMap:
        jenkins: !!com.boxboat.jenkins.library.notify.SlackJenkinsAppNotifyTarget
          channel: "#jenkins"
      successKeys:
        - default
        - jenkins
      successTargets:
        - !!com.boxboat.jenkins.library.notify.SlackJenkinsAppNotifyTarget
          channel: "#jenkins"
      failureKeys:
        - default
        - jenkins
      failureTargets:
        - !!com.boxboat.jenkins.library.notify.SlackJenkinsAppNotifyTarget
          channel: "#jenkins"
      infoKeys:
        - default
        - jenkins
      infoTargets:
        - !!com.boxboat.jenkins.library.notify.SlackJenkinsAppNotifyTarget
          channel: "#jenkins"
    vaultKey: default
    eventRegistryKeys:
      - event: commit/master
        registryKey: default
      - eventRegex: tag/(.*)
        registryKey: default
  promote:
    promotionMap:
      stage:
        event: commit/master
        promoteToEvent: tag/rc
      prod:
        event: tag/rc
        promoteToEvent: tag/release
  deploy:
    deploymentMap:
      dev:
        environmentKey: dev
        event: commit/master
        trigger: true
      stage:
        environmentKey: dev
        event: tag/rc
        trigger: true
      prod:
        environmentKey: prod
        event: tag/release
        trigger: false
